### ISSUE TITLE
Referencing a Library in a DataType document

### ISSUE THREAD

**Issue by yakovkhalinsky** [OneMainF/raml-language-server#20]
Apparently the spec supports this e.g.

```
#%RAML 1.0 DataType

uses:
  Types: library.raml

properties:
  foo: Types.Foo
```

But the language server shows a reference error.

Am I either doing it wrong, or is this simply an unsupported part of the spec in the language server?
